Task 1

In [4]:
import numpy as np
@np.vectorize
def to_Celcius(arr):
    arr_c = (arr - 32) * 5/9
    return arr_c
arr = np.array([32, 68, 100, 212, 77])
print(to_Celcius(arr))

[  0.          20.          37.77777778 100.          25.        ]


Task 2

In [5]:
@np.vectorize
def power_of_number(arr1, arr2):
    arr3 = arr1 ** arr2
    return arr3

arr1 = np.array([2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4])
print(power_of_number(arr1, arr2))

[  2   9  64 625]


Task 3

In [3]:
import numpy as np
arr3 = np.array([
    [4,5,6],
    [3,-1,1],
    [2,1,-2]
])

arr4 = np.array([7,4,5])

result3 = np.linalg.solve(arr3, arr4)
print(result3)

[ 1.7027027   0.62162162 -0.48648649]


Task 4

In [4]:
arr4_1 = np.array([
    [10,-2,3],
    [-2,8,-1],
    [3,-1,6]
])

arr4_2 = np.array([12,-5, 15])
result4 = np.linalg.solve(arr4_1, arr4_2)
print(result4)

[ 0.48963731 -0.2253886   2.21761658]
