In [2]:
#Task1
import numpy as np

np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
#Task2
arr2 = np.arange(0, 9)
a2 = arr2.reshape(3, 3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [29]:
#Task3
arr3 = np.eye(3, dtype=int)
print(arr3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [39]:
#Task4
arr4 = np.random.rand(3,3,3)
print(arr4)

[[[0.95746814 0.40866922 0.72135129]
  [0.10035254 0.25871006 0.25443216]
  [0.6147929  0.89159475 0.86504397]]

 [[0.91283342 0.4157781  0.04182445]
  [0.8587963  0.67080579 0.64631425]
  [0.02621918 0.04203435 0.50487193]]

 [[0.86461203 0.68681761 0.8181757 ]
  [0.1332607  0.09574087 0.15379386]
  [0.6376202  0.39344704 0.67912863]]]


In [40]:
#Task5
arr5 = np.random.rand(10,10)
print(arr5)
print(arr5.min())
print(arr5.max())

[[0.71981693 0.05295395 0.49271335 0.50268427 0.36871313 0.39262744
  0.865147   0.42602728 0.90932356 0.66165494]
 [0.19124689 0.88040229 0.35460381 0.89996904 0.99115194 0.44466381
  0.92052195 0.71626316 0.09125347 0.63795445]
 [0.04088202 0.31706176 0.9864137  0.80035985 0.66599007 0.77818161
  0.83458292 0.07564747 0.51019218 0.44276948]
 [0.88498718 0.55804285 0.51148969 0.22874411 0.34551503 0.2044362
  0.49651774 0.14417137 0.08202343 0.25534968]
 [0.98693482 0.67620683 0.53559145 0.95426181 0.7635937  0.41669084
  0.7350574  0.54447499 0.41804618 0.91974842]
 [0.55838921 0.51190637 0.60372235 0.6491167  0.00692045 0.57957797
  0.53287728 0.95295639 0.94929819 0.88816389]
 [0.51779774 0.71512703 0.64482184 0.39089217 0.86701074 0.7122184
  0.16929243 0.69980403 0.2663545  0.27205107]
 [0.95311264 0.23923244 0.92931383 0.12061367 0.04157287 0.6734919
  0.25048238 0.7352503  0.46516043 0.68672288]
 [0.19659538 0.43092271 0.09240501 0.88463676 0.42043011 0.49780743
  0.32476037 0.

In [42]:
#Task6
vector = np.random.rand(30)
print(vector)
print(vector.mean())

[0.02099063 0.43461895 0.20087206 0.28087762 0.80101636 0.6779075
 0.75930849 0.47068847 0.81272225 0.57317137 0.60693559 0.09715014
 0.74048281 0.76527151 0.80717145 0.21094957 0.73623342 0.80959334
 0.49497417 0.58022893 0.77085642 0.01675952 0.63813645 0.86647461
 0.91397405 0.1337551  0.71800932 0.2710465  0.37345689 0.27012555]
0.5284586362550543


In [ ]:
#Task7
#Min-Max Normalization
arr7 = np.random.randint(0, 10, size=(5,5), dtype=int)

normalized = (arr7 - arr7.min()) / (arr7.max() - arr7.min())
print(normalized)

[[0.22222222 0.11111111 0.44444444 1.         0.88888889]
 [0.22222222 0.77777778 0.11111111 0.         0.55555556]
 [0.22222222 0.88888889 0.22222222 0.         0.88888889]
 [0.55555556 0.11111111 0.22222222 0.55555556 0.        ]
 [0.88888889 0.22222222 0.         0.88888889 0.11111111]]


In [47]:
#Task8
arr8_1 = np.random.randint(0, 10, size=(5,3), dtype=int)
arr8_2 = np.random.randint(0, 10, size=(3,2), dtype=int)

result = np.dot(arr8_1, arr8_2)
print(result)

[[ 65  22]
 [ 87  36]
 [ 85  31]
 [113  45]
 [ 62  24]]


In [49]:
#Task9
arr9_1 = np.array([
    [1, 2, 9],
    [3, 4, 8],
    [5, 6, 7]
])

arr9_2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = arr9_1.dot(arr9_2)
print(result)

[[ 72  84  96]
 [ 75  90 105]
 [ 78  96 114]]


In [ ]:
#Task10
arr10 = np.random.randint(0, 10, size=(4,4), dtype=int)
print(arr10.T)

[[3 0 1 0]
 [3 3 7 7]
 [0 3 7 1]
 [5 0 1 3]]
[[3 3 0 5]
 [0 3 3 0]
 [1 7 7 1]
 [0 7 1 3]]


In [53]:
#Task11
arr11 = np.random.randint(0, 10, size=(3,3), dtype=int)
det = np.linalg.det(arr11)
print(det)

-88.00000000000003


In [54]:
#Task12
A = np.random.randint(0, 10, size=(3,4), dtype=int)
B = np.random.randint(0, 10, size=(4,3), dtype=int)

result = np.dot(A, B)
print(result)

[[ 96 155 130]
 [ 83 121 145]
 [ 67 134 108]]


In [57]:
#Task13
matrix = np.random.randint(0, 10, size=(3,3), dtype=int)
column_vector = np.random.randint(0, 10, size=(3,1), dtype=int)

result = np.dot(matrix, column_vector)
print(result)

[[99]
 [67]
 [25]]


In [58]:
#Task14
A = np.random.randint(0, 10, size=(3,3), dtype=int)
b = np.random.randint(0, 10, size=(3,1), dtype=int)

x = A.transpose().dot(b)
print(x)

[[29]
 [24]
 [30]]


In [ ]:
#Task15
arr15 = np.array([
        [6,8,8,3,6],
        [1,4,5,3,4],
        [4,2,8,4,6],
        [8,6,5,4,9],
        [2,5,7,8,4]])

print(arr15.sum(axis=1)) #Row-wise sum
print(arr15.sum(axis=0)) #Column-wise sum

[[6 8 8 3 6]
 [1 4 5 3 4]
 [4 2 8 4 6]
 [8 6 5 4 9]
 [2 5 7 8 4]]
[31 17 24 32 26]
[21 25 33 22 29]
